"""empty message

Revision ID: 00fd219bf242
Revises: d8be38d77029
Create Date: 2020-04-23 13:04:56.485419

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '00fd219bf242'
down_revision = 'd8be38d77029'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('isVerify')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isVerify', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True, comment='是否通过审核 1-通过 0-未通过'))

    # ### end Alembic commands ###
