"""empty message

Revision ID: 060706fd9e86
Revises: e4e0f40128ca
Create Date: 2020-05-06 15:31:06.099029

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '060706fd9e86'
down_revision = 'e4e0f40128ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snow_child')
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('testUnique', sa.String(length=20), nullable=True, comment='测试是否唯一'))
        batch_op.create_unique_constraint(None, ['testUnique'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('testUnique')

    op.create_table('snow_child',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False, comment='关联的公司用户id'),
    sa.Column('name', mysql.VARCHAR(length=20), nullable=True, comment='测试名字'),
    sa.Column('num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='测试数字'),
    sa.PrimaryKeyConstraint('id'),
    comment='雪花算法子表',
    mysql_comment='雪花算法子表',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
