"""empty message

Revision ID: 0ac5532ed7db
Revises: 76c65e2095b7
Create Date: 2020-04-09 16:30:13.184237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ac5532ed7db'
down_revision = '76c65e2095b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('creator', sa.BigInteger(), nullable=True, comment='创建人'),
    sa.Column('creatTime', sa.Integer(), nullable=True, comment='创建时间'),
    sa.Column('reviseTime', sa.Integer(), nullable=True, comment='更新时间'),
    sa.Column('reviser', sa.BigInteger(), nullable=True, comment='修改人'),
    sa.Column('isDel', sa.SmallInteger(), nullable=True, comment='是否删除 1-删除 0-未删除'),
    sa.Column('tittle', sa.String(length=50), nullable=True, comment='工作的标题'),
    sa.Column('reward', sa.String(length=20), nullable=True, comment='报酬'),
    sa.Column('place', sa.String(length=20), nullable=True, comment='地点'),
    sa.Column('settlement', sa.SmallInteger(), nullable=False, comment='工作结算方式 1-日结 2-周结 3-完工结'),
    sa.Column('isBagEating', sa.SmallInteger(), nullable=False, comment='是否包吃 1-是 2-否'),
    sa.Column('encase', sa.SmallInteger(), nullable=False, comment='是否包住 1-是 2-否'),
    sa.Column('isTrafficSubsidy', sa.SmallInteger(), nullable=False, comment='是否有交通补贴 1-是 2-否'),
    sa.Column('royalty', sa.SmallInteger(), nullable=False, comment='是否有提成 1-是 2-否'),
    sa.PrimaryKeyConstraint('id'),
    comment='300 工作表'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job')
    # ### end Alembic commands ###
