"""添加雪花子表

Revision ID: 0c593507ab0e
Revises: f339204ee140
Create Date: 2020-04-28 13:06:21.278837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c593507ab0e'
down_revision = 'f339204ee140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Snow_Child',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='关联的公司用户id'),
    sa.Column('name', sa.String(length=20), nullable=True, comment='测试名字'),
    sa.Column('num', sa.Integer(), nullable=True, comment='测试数字'),
    sa.PrimaryKeyConstraint('id'),
    comment='雪花算法子表'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Snow_Child')
    # ### end Alembic commands ###
