"""empty message

Revision ID: 104bed3029f3
Revises: 2cdf5b59e39c
Create Date: 2020-04-19 14:16:52.523736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '104bed3029f3'
down_revision = '2cdf5b59e39c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isVerify', sa.SmallInteger(), nullable=True, comment='是否通过审核 1-通过 0-未通过'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('isVerify')

    # ### end Alembic commands ###
