"""empty message

Revision ID: 13bfb39ec6a4
Revises: df1c30bff970
Create Date: 2020-04-13 14:39:08.535843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13bfb39ec6a4'
down_revision = 'df1c30bff970'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_signup',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('creator', sa.BigInteger(), nullable=True, comment='创建人'),
    sa.Column('creatTime', sa.Integer(), nullable=True, comment='创建时间'),
    sa.Column('reviseTime', sa.Integer(), nullable=True, comment='更新时间'),
    sa.Column('reviser', sa.BigInteger(), nullable=True, comment='修改人'),
    sa.Column('isDel', sa.SmallInteger(), nullable=True, comment='是否删除 1-删除 0-未删除'),
    sa.Column('stuId', sa.BigInteger(), nullable=True, comment='申请学生的id号'),
    sa.Column('jobId', sa.BigInteger(), nullable=True, comment='申请工作的id号'),
    sa.Column('message', sa.String(length=200), nullable=True, comment='学生给企业的留言'),
    sa.PrimaryKeyConstraint('id'),
    comment='301 工作表'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_signup')
    # ### end Alembic commands ###
