"""empty message

Revision ID: 22c699b3afa7
Revises: c075bc339c95
Create Date: 2020-04-19 19:22:44.844470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22c699b3afa7'
down_revision = 'c075bc339c95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.SmallInteger(), nullable=True, comment='当前状态 1-待审批 2-进行中 3-已结束'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
