"""empty message

Revision ID: 2cdf5b59e39c
Revises: 8e5a87c3b3da
Create Date: 2020-04-19 14:07:52.579086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cdf5b59e39c'
down_revision = '8e5a87c3b3da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('briefIntroduction', sa.String(length=500), nullable=True, comment='简介'))
        batch_op.add_column(sa.Column('email', sa.String(length=50), nullable=True, comment='企业邮箱'))
        batch_op.add_column(sa.Column('industry', sa.String(length=50), nullable=True, comment='所属行业'))
        batch_op.add_column(sa.Column('line', sa.String(length=80), nullable=True, comment='企业电话'))
        batch_op.add_column(sa.Column('nativePlace', sa.String(length=50), nullable=True, comment='所在城市'))
        batch_op.add_column(sa.Column('phoneNumber', sa.String(length=80), nullable=True, comment='联系人手机号'))
        batch_op.add_column(sa.Column('withPeople', sa.String(length=20), nullable=True, comment='联系人姓名'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('withPeople')
        batch_op.drop_column('phoneNumber')
        batch_op.drop_column('nativePlace')
        batch_op.drop_column('line')
        batch_op.drop_column('industry')
        batch_op.drop_column('email')
        batch_op.drop_column('briefIntroduction')

    # ### end Alembic commands ###
