"""empty message

Revision ID: 448a21fc9380
Revises: 53de405e38df
Create Date: 2020-04-15 19:41:33.617786

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '448a21fc9380'
down_revision = '53de405e38df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume_other', sa.Column('isFullTime', sa.SmallInteger(), nullable=True, comment='是否支持全职上班 1-是 0-否'))
    op.alter_column('resume_other', 'expectedJobType',
               existing_type=mysql.VARCHAR(length=50),
               comment='期望工作类型',
               existing_comment='开始时间',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resume_other', 'expectedJobType',
               existing_type=mysql.VARCHAR(length=50),
               comment='开始时间',
               existing_comment='期望工作类型',
               existing_nullable=True)
    op.drop_column('resume_other', 'isFullTime')
    # ### end Alembic commands ###
