"""empty message

Revision ID: 537fc75ee9fa
Revises: 68af3e3210d4
Create Date: 2020-04-22 19:26:58.122245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '537fc75ee9fa'
down_revision = '68af3e3210d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('com_sign',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('creator', sa.BigInteger(), nullable=True, comment='创建人'),
    sa.Column('creatTime', sa.Integer(), nullable=True, comment='创建时间'),
    sa.Column('reviseTime', sa.Integer(), nullable=True, comment='更新时间'),
    sa.Column('reviser', sa.BigInteger(), nullable=True, comment='修改人'),
    sa.Column('isDel', sa.SmallInteger(), nullable=True, comment='是否删除 1-删除 0-未删除'),
    sa.Column('uId', sa.BigInteger(), nullable=True, comment='关联的公司用户id'),
    sa.Column('cId', sa.BigInteger(), nullable=True, comment='关联的公司id'),
    sa.Column('isVerify', sa.SmallInteger(), nullable=True, comment='是否通过审核 1-通过 0-未通过'),
    sa.PrimaryKeyConstraint('id'),
    comment='309 公司信息提交审核记录表'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('com_sign')
    # ### end Alembic commands ###
