"""empty message

Revision ID: 53de405e38df
Revises: 2065e835c502
Create Date: 2020-04-14 23:05:58.017231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53de405e38df'
down_revision = '2065e835c502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_edu',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('creator', sa.BigInteger(), nullable=True, comment='创建人'),
    sa.Column('creatTime', sa.Integer(), nullable=True, comment='创建时间'),
    sa.Column('reviseTime', sa.Integer(), nullable=True, comment='更新时间'),
    sa.Column('reviser', sa.BigInteger(), nullable=True, comment='修改人'),
    sa.Column('isDel', sa.SmallInteger(), nullable=True, comment='是否删除 1-删除 0-未删除'),
    sa.Column('userId', sa.BigInteger(), nullable=True, comment='关联userId号'),
    sa.Column('school', sa.String(length=100), nullable=True, comment='学校'),
    sa.Column('major', sa.String(length=50), nullable=True, comment='专业'),
    sa.Column('degree', sa.String(length=50), nullable=True, comment='学历'),
    sa.Column('startTime', sa.String(length=50), nullable=True, comment='开始时间'),
    sa.Column('endTime', sa.String(length=50), nullable=True, comment='结束时间'),
    sa.Column('experience', sa.String(length=500), nullable=True, comment='在校经历'),
    sa.PrimaryKeyConstraint('id'),
    comment='304 教育经历表'
    )
    op.create_table('resume_other',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('creator', sa.BigInteger(), nullable=True, comment='创建人'),
    sa.Column('creatTime', sa.Integer(), nullable=True, comment='创建时间'),
    sa.Column('reviseTime', sa.Integer(), nullable=True, comment='更新时间'),
    sa.Column('reviser', sa.BigInteger(), nullable=True, comment='修改人'),
    sa.Column('isDel', sa.SmallInteger(), nullable=True, comment='是否删除 1-删除 0-未删除'),
    sa.Column('userId', sa.BigInteger(), nullable=True, comment='关联userId号'),
    sa.Column('expectedJobType', sa.String(length=50), nullable=True, comment='开始时间'),
    sa.Column('shortJobTime', sa.String(length=50), nullable=True, comment='短期工作时间'),
    sa.Column('ableWorkDay', sa.String(length=50), nullable=True, comment='可上班时间'),
    sa.Column('selfIntroduction', sa.String(length=500), nullable=True, comment='自我介绍'),
    sa.PrimaryKeyConstraint('id'),
    comment='306 简历其他项'
    )
    op.create_table('resume_work',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('creator', sa.BigInteger(), nullable=True, comment='创建人'),
    sa.Column('creatTime', sa.Integer(), nullable=True, comment='创建时间'),
    sa.Column('reviseTime', sa.Integer(), nullable=True, comment='更新时间'),
    sa.Column('reviser', sa.BigInteger(), nullable=True, comment='修改人'),
    sa.Column('isDel', sa.SmallInteger(), nullable=True, comment='是否删除 1-删除 0-未删除'),
    sa.Column('userId', sa.BigInteger(), nullable=True, comment='关联userId号'),
    sa.Column('company', sa.String(length=100), nullable=True, comment='公司名'),
    sa.Column('startTime', sa.String(length=50), nullable=True, comment='开始时间'),
    sa.Column('endTime', sa.String(length=50), nullable=True, comment='结束时间'),
    sa.Column('experience', sa.String(length=500), nullable=True, comment='在职经历'),
    sa.PrimaryKeyConstraint('id'),
    comment='306 工作经历表'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resume_work')
    op.drop_table('resume_other')
    op.drop_table('resume_edu')
    # ### end Alembic commands ###
