"""empty message

Revision ID: 5708bef22c2f
Revises: 448a21fc9380
Create Date: 2020-04-16 13:26:17.260809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5708bef22c2f'
down_revision = '448a21fc9380'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('cId', sa.BigInteger(), nullable=True, comment='企业的id号'))
    op.add_column('job', sa.Column('email', sa.String(length=20), nullable=True, comment='企业联系人邮箱'))
    op.add_column('job', sa.Column('phone', sa.String(length=20), nullable=True, comment='企业联系人电话'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'phone')
    op.drop_column('job', 'email')
    op.drop_column('job', 'cId')
    # ### end Alembic commands ###
