"""empty message

Revision ID: 5a5d28dae37f
Revises: 00fd219bf242
Create Date: 2020-04-23 13:05:31.421385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a5d28dae37f'
down_revision = '00fd219bf242'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isVerify', sa.SmallInteger(), nullable=True, comment='是否通过审核 1-待审核 2-通过 3-未通过'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('isVerify')

    # ### end Alembic commands ###
