"""empty message

Revision ID: 6018fa1854e8
Revises: a0ecf159b1d7
Create Date: 2020-04-11 12:54:16.375526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6018fa1854e8'
down_revision = 'a0ecf159b1d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'job',
        ' 工作表',
        existing_comment='300 工作表',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'job',
        '300 工作表',
        existing_comment=' 工作表',
        schema=None
    )
    # ### end Alembic commands ###
