"""empty message

Revision ID: 68702b2d54e3
Revises: 9dd17884eb89
Create Date: 2020-04-19 13:24:12.955661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68702b2d54e3'
down_revision = '9dd17884eb89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('creator', sa.BigInteger(), nullable=True, comment='创建人'),
    sa.Column('creatTime', sa.Integer(), nullable=True, comment='创建时间'),
    sa.Column('reviseTime', sa.Integer(), nullable=True, comment='更新时间'),
    sa.Column('reviser', sa.BigInteger(), nullable=True, comment='修改人'),
    sa.Column('isDel', sa.SmallInteger(), nullable=True, comment='是否删除 1-删除 0-未删除'),
    sa.Column('cname', sa.String(length=20), nullable=True, comment='公司的名字'),
    sa.PrimaryKeyConstraint('id'),
    comment='307 公司信息表'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company')
    # ### end Alembic commands ###
