"""empty message

Revision ID: 68af3e3210d4
Revises: 65998dee204f
Create Date: 2020-04-22 15:50:32.223694

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '68af3e3210d4'
down_revision = '65998dee204f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_signup', schema=None) as batch_op:
        batch_op.drop_column('isVerify')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_signup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isVerify', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True, comment='是否通过 1-通过 2-不通过'))

    # ### end Alembic commands ###
