"""empty message

Revision ID: 722222df86fe
Revises: 5a5d28dae37f
Create Date: 2020-04-24 12:33:36.261767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '722222df86fe'
down_revision = '5a5d28dae37f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Snow_Test',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='关联的公司用户id'),
    sa.Column('name', sa.String(length=20), nullable=True, comment='测试名字'),
    sa.PrimaryKeyConstraint('id'),
    comment='雪花算法基础表'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Snow_Test')
    # ### end Alembic commands ###
