"""empty message

Revision ID: 73954808de95
Revises: 22c699b3afa7
Create Date: 2020-04-20 11:42:00.917052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73954808de95'
down_revision = '22c699b3afa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('openId', sa.String(length=300), nullable=True, comment='微信小程序用户唯一标识id'))
        batch_op.create_unique_constraint(None, ['openId'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('openId')

    # ### end Alembic commands ###
