"""empty message

Revision ID: 75c41d029df0
Revises: 13bfb39ec6a4
Create Date: 2020-04-13 14:41:00.747604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75c41d029df0'
down_revision = '13bfb39ec6a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('signNum', sa.Integer(), nullable=True, comment='当前报名人数人数'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'signNum')
    # ### end Alembic commands ###
