"""empty message

Revision ID: 8e5a87c3b3da
Revises: 0438ac5f93d2
Create Date: 2020-04-19 14:02:20.390494

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8e5a87c3b3da'
down_revision = '0438ac5f93d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True, comment='用户的年龄'))
        batch_op.add_column(sa.Column('bestEdu', sa.String(length=20), nullable=True, comment='最高学历'))
        batch_op.add_column(sa.Column('birthday', sa.String(length=50), nullable=True, comment='生日'))
        batch_op.add_column(sa.Column('eduStatus', sa.SmallInteger(), nullable=True, comment='教育状态 1-在读 2-已毕业'))
        batch_op.add_column(sa.Column('email', sa.String(length=50), nullable=True, comment='邮箱'))
        batch_op.add_column(sa.Column('height', sa.String(length=50), nullable=True, comment='身高'))
        batch_op.add_column(sa.Column('nativePlace', sa.String(length=50), nullable=True, comment='所在城市'))
        batch_op.add_column(sa.Column('phoneNumber', sa.String(length=80), nullable=True, comment='手机号'))
        batch_op.add_column(sa.Column('place', sa.String(length=50), nullable=True, comment='所在地级市'))
        batch_op.add_column(sa.Column('qqNum', sa.String(length=20), nullable=True, comment='QQ'))
        batch_op.add_column(sa.Column('weChat', sa.String(length=50), nullable=True, comment='微信号'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('name')
        batch_op.drop_column('phoneNumber')
        batch_op.drop_column('eduStatus')
        batch_op.drop_column('qqNum')
        batch_op.drop_column('nativePlace')
        batch_op.drop_column('email')
        batch_op.drop_column('bestEdu')
        batch_op.drop_column('height')
        batch_op.drop_column('birthday')
        batch_op.drop_column('weChat')
        batch_op.drop_column('age')
        batch_op.drop_column('place')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('place', mysql.VARCHAR(length=50), nullable=True, comment='所在地级市'))
        batch_op.add_column(sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='用户的年龄'))
        batch_op.add_column(sa.Column('weChat', mysql.VARCHAR(length=50), nullable=True, comment='微信号'))
        batch_op.add_column(sa.Column('birthday', mysql.VARCHAR(length=50), nullable=True, comment='生日'))
        batch_op.add_column(sa.Column('height', mysql.VARCHAR(length=50), nullable=True, comment='身高'))
        batch_op.add_column(sa.Column('bestEdu', mysql.VARCHAR(length=20), nullable=True, comment='最高学历'))
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(length=50), nullable=True, comment='邮箱'))
        batch_op.add_column(sa.Column('nativePlace', mysql.VARCHAR(length=50), nullable=True, comment='所在城市'))
        batch_op.add_column(sa.Column('qqNum', mysql.VARCHAR(length=20), nullable=True, comment='QQ'))
        batch_op.add_column(sa.Column('eduStatus', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True, comment='教育状态 1-在读 2-已毕业'))
        batch_op.add_column(sa.Column('phoneNumber', mysql.VARCHAR(length=80), nullable=True, comment='手机号'))
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=50), nullable=True, comment='用户的姓名'))

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('weChat')
        batch_op.drop_column('qqNum')
        batch_op.drop_column('place')
        batch_op.drop_column('phoneNumber')
        batch_op.drop_column('nativePlace')
        batch_op.drop_column('height')
        batch_op.drop_column('email')
        batch_op.drop_column('eduStatus')
        batch_op.drop_column('birthday')
        batch_op.drop_column('bestEdu')
        batch_op.drop_column('age')

    # ### end Alembic commands ###
