"""empty message

Revision ID: 9dd17884eb89
Revises: 5708bef22c2f
Create Date: 2020-04-19 11:01:42.090533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dd17884eb89'
down_revision = '5708bef22c2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.SmallInteger(), nullable=True, comment='身份类型 1-系统管理员 2-企业 3-学生'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
