"""empty message

Revision ID: a86919c9c621
Revises: 060706fd9e86
Create Date: 2020-05-07 14:03:53.053723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a86919c9c621'
down_revision = '060706fd9e86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('com_sign2',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='主键id'),
    sa.Column('name', sa.String(length=80), nullable=True, comment='名字'),
    sa.PrimaryKeyConstraint('id'),
    comment='309 公司信息提交审核记录表'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('com_sign2')
    # ### end Alembic commands ###
