"""empty message

Revision ID: b4993ef6a4e4
Revises: ed4b9404fbb0
Create Date: 2020-04-14 10:16:36.115751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4993ef6a4e4'
down_revision = 'ed4b9404fbb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_signup', sa.Column('status', sa.SmallInteger(), nullable=True, comment='状态 1-已报名 2-已录用 3-已到岗 4-已结算'))
    op.create_table_comment(
        'job_signup',
        '302 提交工作记录表',
        existing_comment='301 工作表',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'job_signup',
        '301 工作表',
        existing_comment='302 提交工作记录表',
        schema=None
    )
    op.drop_column('job_signup', 'status')
    # ### end Alembic commands ###
