"""empty message

Revision ID: c075bc339c95
Revises: 104bed3029f3
Create Date: 2020-04-19 14:49:41.085759

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c075bc339c95'
down_revision = '104bed3029f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cemail', sa.String(length=50), nullable=True, comment='企业邮箱'))
        batch_op.add_column(sa.Column('cinfo', sa.String(length=500), nullable=True, comment='简介'))
        batch_op.add_column(sa.Column('cphone', sa.String(length=80), nullable=True, comment='企业电话'))
        batch_op.add_column(sa.Column('cplace', sa.String(length=50), nullable=True, comment='所在城市'))
        batch_op.add_column(sa.Column('ctype', sa.String(length=50), nullable=True, comment='所属行业'))
        batch_op.add_column(sa.Column('pname', sa.String(length=20), nullable=True, comment='联系人姓名'))
        batch_op.add_column(sa.Column('pphone', sa.String(length=80), nullable=True, comment='联系人手机号'))
        batch_op.drop_column('email')
        batch_op.drop_column('line')
        batch_op.drop_column('phoneNumber')
        batch_op.drop_column('nativePlace')
        batch_op.drop_column('industry')
        batch_op.drop_column('briefIntroduction')
        batch_op.drop_column('withPeople')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('withPeople', mysql.VARCHAR(length=20), nullable=True, comment='联系人姓名'))
        batch_op.add_column(sa.Column('briefIntroduction', mysql.VARCHAR(length=500), nullable=True, comment='简介'))
        batch_op.add_column(sa.Column('industry', mysql.VARCHAR(length=50), nullable=True, comment='所属行业'))
        batch_op.add_column(sa.Column('nativePlace', mysql.VARCHAR(length=50), nullable=True, comment='所在城市'))
        batch_op.add_column(sa.Column('phoneNumber', mysql.VARCHAR(length=80), nullable=True, comment='联系人手机号'))
        batch_op.add_column(sa.Column('line', mysql.VARCHAR(length=80), nullable=True, comment='企业电话'))
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(length=50), nullable=True, comment='企业邮箱'))
        batch_op.drop_column('pphone')
        batch_op.drop_column('pname')
        batch_op.drop_column('ctype')
        batch_op.drop_column('cplace')
        batch_op.drop_column('cphone')
        batch_op.drop_column('cinfo')
        batch_op.drop_column('cemail')

    # ### end Alembic commands ###
