"""empty message

Revision ID: d9307a4c2810
Revises: 537fc75ee9fa
Create Date: 2020-04-22 19:56:04.787916

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd9307a4c2810'
down_revision = '537fc75ee9fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('com_sign', schema=None) as batch_op:
        batch_op.drop_column('isVerify')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('com_sign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isVerify', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True, comment='是否通过审核 1-通过 0-未通过'))

    # ### end Alembic commands ###
