"""empty message

Revision ID: df1c30bff970
Revises: 15838d798d7c
Create Date: 2020-04-13 10:56:45.451580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df1c30bff970'
down_revision = '15838d798d7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('browseTimes', sa.Integer(), nullable=True, comment='浏览次数'))
    op.add_column('job', sa.Column('content', sa.String(length=500), nullable=True, comment='工作内容'))
    op.add_column('job', sa.Column('detailPlace', sa.String(length=20), nullable=True, comment='详细地址'))
    op.add_column('job', sa.Column('endTime', sa.String(length=80), nullable=True, comment='结束时间'))
    op.add_column('job', sa.Column('fromCompany', sa.String(length=80), nullable=True, comment='发布的企业'))
    op.add_column('job', sa.Column('recruitNum', sa.Integer(), nullable=True, comment='招聘人数'))
    op.add_column('job', sa.Column('sex', sa.String(length=20), nullable=True, comment='性别要求 1-男 2-女 3-男女不限'))
    op.add_column('job', sa.Column('startTime', sa.String(length=80), nullable=True, comment='开始时间'))
    op.add_column('job', sa.Column('type', sa.String(length=20), nullable=True, comment='工作类型'))
    op.add_column('job', sa.Column('withPeople', sa.String(length=20), nullable=True, comment='企业联系人'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'withPeople')
    op.drop_column('job', 'type')
    op.drop_column('job', 'startTime')
    op.drop_column('job', 'sex')
    op.drop_column('job', 'recruitNum')
    op.drop_column('job', 'fromCompany')
    op.drop_column('job', 'endTime')
    op.drop_column('job', 'detailPlace')
    op.drop_column('job', 'content')
    op.drop_column('job', 'browseTimes')
    # ### end Alembic commands ###
