"""empty message

Revision ID: dfa694f4994d
Revises: 73954808de95
Create Date: 2020-04-22 00:28:13.387413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfa694f4994d'
down_revision = '73954808de95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sex', sa.SmallInteger(), nullable=True, comment='性别 1-男 2-女'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('sex')

    # ### end Alembic commands ###
